### ISSUE TITLE
The app downsize on save

### ISSUE THREAD

**Issue by ryonakano** [aharotias2/parapara#14]
## What Happened
The app seems to downsize the photo when saving. I used [this photo](https://unsplash.com/photos/7fL7YEQMltg) for testing.

### Original
![Screenshot from 2021-01-02 21-10-51](https://user-images.githubusercontent.com/26003928/103457077-6e13c580-4d3f-11eb-9292-b7bd44ef5988.png)

### Edited
![Screenshot from 2021-01-02 21-10-53](https://user-images.githubusercontent.com/26003928/103457076-6d7b2f00-4d3f-11eb-911b-30f40354d9bc.png)

## Expected Behavior
The size of photos should not be changed before/after editing.

**Comment by aharotias2** [comment]
I'm sorry, this is by design. The image will be saved in the size currently displayed. It may be unfriendly. I will consider changing specifications.

**Comment by ryonakano** [comment]
Fixed in c62f3bc
