### ISSUE TITLE
Create the deb-packaging branch

### ISSUE THREAD

**Issue by ryonakano** [aharotias2/parapara#18]
This is required to publish the app to AppCenter. Clone https://github.com/elementary/debian-template and push to this repo with the following name `deb-packaging`.

**Comment by aharotias2** [comment]
I created deb-packaging branch. The task has been done, right?

**Comment by ryonakano** [comment]
Nope, I mean the `deb-packaging` branch just include the content of `debian-template` repo like [this repo](https://github.com/ryonakano/reco/tree/deb-packaging) and the `master` should keep as it is.

Actually, however, the both of the following ways works:

- Set up `deb-packaging` branch (which I recommended)
- Put the debian folder in the `master` branch

You put the debian folder in the both `master` and `deb-packaging`, so it might be easy to leave the master branch and just delete the `deb-packaging` branch like [this repo](https://github.com/manexim/typewriter).

Sorry, my instruction is not enough :bowing_woman:

**Comment by aharotias2** [comment]
Thank you for your information.
I will try again.

**Comment by aharotias2** [comment]
I understand this time. Thank you for taking the time.
I took the first way you recommended.
I pushed fix commits to master and deb-package.
If there are no mistakes, please close this issue.

**Comment by ryonakano** [comment]
Yeah it looks good now. Thank you too :smile:
