### ISSUE TITLE
Publish to AppCenter on elementary OS

### ISSUE THREAD

**Issue by ryonakano** [aharotias2/parapara#2]
Hi! I suggest you to make this app available on AppCenter in [elementary OS](https://elementary.io/) which has a similar structure with AppStore in macOS—you request a review from elementary OS developers and they review the app. If they approve it users can install it on AppCenter.

The main reason that I suggest this is the complexity of [Photos app](https://github.com/elementary/photos) on elementary OS which is sipped by default. It has really complex code structure and looks stacked to keep maintained, e.g. it still can't open animated gif files. However, your app is simple and really works great as a photo viewer. I think it would be what users on elementary OS want if your app supports more image formats including animated gif.

188 apps designed for elementary OS are available on AppCenter at the moment: https://appcenter.elementary.io/
(and I develop 2 of them: [Reco](https://github.com/ryonakano/reco) and [Konbucase](https://github.com/ryonakano/konbucase) 😁).

You have some merits by doing this:

- Your app would be spread to people who loves elementary OS around the world
- Developers or app translators can contribute to your app with feature improvements, bug fixes, and translations
- You may get more fan-base
- You can monetize the app if you want or keep it for free

You already wrote your app in Vala/GTK so it's easy to publish it to AppCenter, although there are some to-dos IMO:

- [x] Organize the directory
- [x] Use Meson instead of Make for the build system
- [x] Support localization with gettext
- [x] Add an app icon
- [x] Add .appdata.xml file
- [x] (Supports more image formats including animated gif)
- [ ] Create a new release on GitHub
- [ ] Log in to https://developer.elementary.io/ with your GitHub account
- [ ] Click "Submit"

I'd like to help you to work on these processes if you need.

What do you think?

**Comment by aharotias2** [comment]
Hi, Ryo.
I will try to do what you have suggested one by one.
it is great if my app will be registered by elementary OS.
Thank you for your great idea!

**Comment by ryonakano** [comment]
Hi @aharotias2, thank you for adding the support of animated gif! It works really nice and is definitely an advantage of your app against the Photos on elementary OS. I'm really excited your app getting improved incredibly these days! :tada:

**Comment by ryonakano** [comment]
Before publishing I recommend you to read the wiki: https://github.com/elementary/houston/wiki

**Comment by ryonakano** [comment]
As seeing the design of your app, your app seems to suit to GNOME rather than elementary OS; I guess you're developing it on Ubuntu? and I feel you should publish to [Flathub](https://flathub.org), rather than AppCenter on elementary OS. At least, you may want to publish it somewhere so that you can get users, contributors, etc. What do you think?

**Comment by ryonakano** [comment]
@aharotias2 Would like to hear your opinion against my comment above.

**Comment by aharotias2** [comment]
Hi, @ryonakano 
Sorry for the late reply. I was thinking about how to answer.
I don't have a policy in myself right now. However, as you say, it seems appropriate to register on Flathub. My development machine uses Xfce for DE on Arch Linux. The application design is imitative and certainly GNOME conscious, but honestly I'm not sure. I recently installed Elementary OS 6 on another machine. I think it's nice to be able to easily install the app from Flathub. However, I'm afraid that only applications with very high functionality and high degree of perfection are registered. Should I create an opportunity to lower the overall level? I have received professional-level cooperation from you. I will try to send a pull request to Flathub as soon as possible. Thank you as always.

**Comment by ryonakano** [comment]
Ah, you use Xfce on Arch Linux! Then maybe you may want to publish on Flathub rather than AppCenter Dashboard for elementary OS. AppCenter Dashboard is designed just only for elementary OS, so you maybe need to prepare an environment that installed elementary OS, while Flathub is designed for all distributions/distributors. elementary OS also supports *sideloading* apps from Flathub so if you publish on Flathub you can provide your app against any distribution users including elementary OS users.

And regarding to the function of apps, you don't need to worry that your app might be unprofessional and imperfect. I feel you have professional skill of Vala and C as far as I saw your code. I have some skill of desktop application development using GTK/Vala, but not good at fundamental things of Vala (like ownership, Pixbuf, etc.) so I really respect your skill. I love your app's appearance and function so am asking you to expose it somewhere 😉 By doing this more users would get intention to your app and someone who want to make it even better might appear, and your app would be polished even more.

If you create a Pull Request on Flathub repository, feel free to mention me so that you get me subscribed and can ask for help. I'll do my best 😌

Thank you for commenting too!

**Comment by ryonakano** [comment]
Closing since the app now in Flathub. Your app looks really neat in GNOME desktop, great work!

**Comment by aharotias2** [comment]
I could not reached this point without your help.
Thank you very much!
