### ISSUE TITLE
Opening the same animated gif causes playback speed faster

### ISSUE THREAD

**Issue by ryonakano** [aharotias2/parapara#20]
## What Happened
https://user-images.githubusercontent.com/26003928/103492014-6e10e400-4e6b-11eb-9485-b50bab851cb8.mp4

Opening the same animated gif causes playback speed faster.

## Expected Behavior
Opening the same animated gif shouldn't change playback speed.

**Comment by aharotias2** [comment]
Thank you for your report. This is a bug. I will fix it.

**Comment by aharotias2** [comment]
I have fixed this issue. Thank you, ryonakano!

**Comment by ryonakano** [comment]
Confirmed it was fixed. Thank you too! :blush:
