### ISSUE TITLE
HeaderButtons: Unify the use of normal and symbolic icons

### ISSUE THREAD

**Issue by ryonakano** [aharotias2/parapara#31]
https://github.com/aharotias2/tatap/blob/2f12db99bec4f364c38d511b3b4477bc942ea480/src/Widgets/HeaderButtons.vala#L50-L59

Here we use `document-open` icon for the open button and `document-save-as-symbolic` icon for the save button. I feel like this is a little cluttered as the use of icons: the former is normal icon and the latter is symbolic one.

I guess we should unify to either type of icon. The icons actually used depend on the icon theme you use though.

## Current
![Screenshot from 2021-01-16 09-44-16](https://user-images.githubusercontent.com/26003928/104792271-2c742780-57e1-11eb-8427-5c3010aa3760.png)

## Normal Only
![Screenshot from 2021-01-16 09-50-54](https://user-images.githubusercontent.com/26003928/104792278-2ed68180-57e1-11eb-8742-1a98d38897a7.png)

## Symbolic Only
![Screenshot from 2021-01-16 09-51-23](https://user-images.githubusercontent.com/26003928/104792279-30a04500-57e1-11eb-8f76-50365253244d.png)

**Comment by aharotias2** [comment]
Hello, @ryonakano.
Thank you for your suggestion
I don't think it's a problem to choose a symbolic only just because all the other icons used in this app are already symbolic.

**Comment by ryonakano** [comment]
Hi, thank you for fixing this.
