### ISSUE TITLE
Support saving files

### ISSUE THREAD

**Issue by ryonakano** [aharotias2/parapara#33]
The app only supports "save as"; it's not possible to override the currently opened image.

**Comment by aharotias2** [comment]
Hi, @ryonakano 
The save dialog had an empty entry on the top of window.
An user should manually set the filename to save to overwrite the current image.
This was inconvenient.
Now, the filename of currently opened image will be set in the entry by default.
You can overwrite it by simply push the save button without changes.
This is a shortest fix (commited at c62f3bc).
If you have any questions or suggestions, feel free to comment.
Thank you.

**Comment by ryonakano** [comment]
Looks nice, thank you for your quick fix!
