### ISSUE TITLE
question on incorporating Debian packaging files

### ISSUE THREAD

**Issue by SwampRabbit** [aharotias2/parapara#44]
Hello, I have created the Debian packaging files necessary to build a .deb package for Debian based distro repos.

This is more of a question than an issue.

How would you like me to submit a PR to incorporate these files:
- would you like to create a branch named "debian packaging" and I submit the debian folder and associated files to that?
OR
- would you like me to submit a PR directly to master branch?

**Comment by aharotias2** [comment]
Hello, we welcome your offer.
Either is fine. If you recommend, I will create a debian-packaging branch.
Should I create a branch from HEAD and delete the files inside?

**Comment by SwampRabbit** [comment]
@aharotias2 it really is up to you, there are two thoughts here:
1) you want to keep distro specific packaging out of your main branch
2) you want to make it easier to package by putting distro specific packaging in your main branch

Since you are including flatpak packaging in your main branch, might as well include Debian, Fedora, Arch packaging files too I guess.  It won't be that many files or take up too much space and it would be easier if someone downloads and wants to build locally too.

If you do want to create a new empty branch, one way to do it is:
```
git checkout --orphan debian-packaging
git rm -rf .
git commit --allow-empty -m "root commit"
git push origin debian-packaging
```
_I don't know if that is the best way, but it works for me on the version of git I use_

**Comment by aharotias2** [comment]
Thank you for the detailed explanation. I learned a lot.
It seems okay to put the Debian files on the main branch.
Feel free to make a pull request to the main branch.

**Comment by SwampRabbit** [comment]
@aharotias2 ok, thanks, I'll prepare a PR soon
